import {Router} from 'express';import mongoose from 'mongoose';import CasePaper from '../models/CasePaper.js';import Prescription from '../models/Prescription.js';import Medicine from '../models/Medicine.js';import Billing from '../models/Billing.js';import Patient from '../models/Patient.js';import Setting from '../models/Setting.js';import {protect,allow} from '../middleware/auth.js';import {logActivity} from '../utils/logActivity.js';
const r=Router();r.use(protect,allow('Admin','Doctor'));
const oid=id=>mongoose.isValidObjectId(id);
async function fee(){return Number((await Setting.findOne({key:'consultation_fee'}))?.value??500)}
async function outstanding(patientId){const rows=await Billing.aggregate([{$match:{patient:new mongoose.Types.ObjectId(patientId)}},{$group:{_id:null,v:{$sum:'$outstanding'}}}]);await Patient.findByIdAndUpdate(patientId,{outstandingAmount:rows[0]?.v||0})}
async function buildItems(items,stockChanges){let medTotal=0;const out=[];for(const i of items||[]){if(!oid(i.medicine))continue;const m=await Medicine.findById(i.medicine);if(!m)continue;const qty=Math.max(0,Number(i.quantity||0));const deducted=Math.min(Number(m.stock||0),qty);if(deducted>0){m.stock=Math.max(0,Number(m.stock||0)-deducted);await m.save();stockChanges.push({id:m._id,qty:deducted})}medTotal+=Number(m.price||0)*qty;out.push({medicine:m._id,comboId:i.comboId||'',unitDose:i.unitDose||'',dosage:i.dosage||'',duration:i.duration||'',quantity:qty,price:Number(m.price||0)})}return{out,medTotal}}
async function billValues(billing,medTotal){const isManual=billing?.mode==='manual';const subtotal=isManual?0:(await fee())+medTotal;const discount=isManual?0:Number(billing?.discount||0);const total=isManual?Math.max(0,Number(billing?.manualAmount||0)):Math.max(0,subtotal-discount);const paid=billing?.status==='Pending'?0:billing?.status==='Partial'?Math.min(total,Math.max(0,Number(billing?.amountPaid||0))):total;return{subtotal,discount,total,isManual,paid,outstanding:Math.max(0,total-paid),status:paid>=total?'Paid':paid>0?'Partial':'Pending'}}

r.get('/:id',async(req,res)=>{const c=await CasePaper.findById(req.params.id).populate('patient').populate('doctor','name role');if(!c)return res.status(404).json({message:'Case not found'});const [p,b]=await Promise.all([Prescription.findOne({casePaper:c._id}).populate('items.medicine'),Billing.findOne({casePaper:c._id}).populate('patient')]);res.json({casePaper:c,prescription:p,billing:b})});
r.post('/',async(req,res)=>{let createdCase,createdPrescription,createdBill;const stockChanges=[];try{const {patientId,clinical={},items=[],billing={}}=req.body;if(!oid(patientId))return res.status(400).json({message:'Invalid patient'});const patient=await Patient.findById(patientId);if(!patient)return res.status(404).json({message:'Patient not found'});if(clinical.allergies!==undefined){patient.allergies=clinical.allergies;await patient.save()}createdCase=await CasePaper.create({...clinical,allergies:undefined,patient:patientId,doctor:req.user._id});const built=await buildItems(items,stockChanges);if(built.out.length)createdPrescription=await Prescription.create({casePaper:createdCase._id,items:built.out});const v=await billValues(billing,built.medTotal);const invoiceNo='INV-'+Date.now().toString().slice(-9);createdBill=await Billing.create({invoiceNo,patient:patientId,casePaper:createdCase._id,subtotal:v.subtotal,discount:v.discount,totalAmount:v.total,isManual:v.isManual,paymentMethod:billing.paymentMethod||'Cash',amountPaid:v.paid,outstanding:v.outstanding,status:v.status,payments:v.paid>0?[{amount:v.paid,paymentMethod:billing.paymentMethod||'Cash',receivedBy:req.user._id,notes:'Payment recorded during consultation'}]:[]});await outstanding(patientId);await logActivity(req,'Consultation Created','case_paper',createdCase._id,`Patient ${patient.name}`);res.status(201).json({casePaper:createdCase,billing:createdBill})}catch(e){try{for(const x of stockChanges)await Medicine.findByIdAndUpdate(x.id,{$inc:{stock:x.qty}});if(createdBill)await Billing.findByIdAndDelete(createdBill._id);if(createdPrescription)await Prescription.findByIdAndDelete(createdPrescription._id);if(createdCase)await CasePaper.findByIdAndDelete(createdCase._id)}catch{}res.status(400).json({message:e.message})}});
r.put('/:id',async(req,res)=>{const c=await CasePaper.findById(req.params.id);if(!c)return res.status(404).json({message:'Case not found'});const prescription=await Prescription.findOne({casePaper:c._id});const oldItems=prescription?.items||[];const newStock=[];try{for(const i of oldItems)if(i.medicine&&i.quantity)await Medicine.findByIdAndUpdate(i.medicine,{$inc:{stock:Number(i.quantity)}});const {clinical={},items=[],billing={},editReason=''}=req.body;if(clinical.allergies!==undefined)await Patient.findByIdAndUpdate(c.patient,{allergies:clinical.allergies});Object.assign(c,{...clinical,allergies:undefined});await c.save();const built=await buildItems(items,newStock);if(prescription){prescription.items=built.out;prescription.editReason=editReason;await prescription.save()}else if(built.out.length)await Prescription.create({casePaper:c._id,items:built.out,editReason});const v=await billValues(billing,built.medTotal);let bill=await Billing.findOne({casePaper:c._id});if(!bill)bill=new Billing({invoiceNo:'INV-'+Date.now().toString().slice(-9),patient:c.patient,casePaper:c._id});bill.subtotal=v.subtotal;bill.discount=v.discount;bill.totalAmount=v.total;bill.isManual=v.isManual;bill.amountPaid=bill.status==='Paid'?v.total:Math.min(Number(bill.amountPaid||0),v.total);bill.outstanding=Math.max(0,v.total-bill.amountPaid);bill.status=bill.outstanding<=.009?'Paid':bill.amountPaid>0?'Partial':'Pending';await bill.save();await outstanding(String(c.patient));await logActivity(req,'Prescription Edit','case_paper',c._id,editReason);res.json({casePaper:c,billing:bill})}catch(e){try{for(const x of newStock)await Medicine.findByIdAndUpdate(x.id,{$inc:{stock:x.qty}});for(const i of oldItems)if(i.medicine&&i.quantity)await Medicine.findByIdAndUpdate(i.medicine,{$inc:{stock:-Number(i.quantity)}})}catch{}res.status(400).json({message:e.message})}});
export default r;
