import {Router} from 'express';import Medicine from '../models/Medicine.js';import {protect,allow} from '../middleware/auth.js';import {logActivity} from '../utils/logActivity.js';import {imageUpload,upload} from '../middleware/upload.js';import {uploadBuffer,deleteCloudinaryAsset} from '../utils/cloudinaryUpload.js';import Papa from 'papaparse';
const r=Router();r.use(protect);const folder=()=>process.env.CLOUDINARY_FOLDER||'ayurvedshala-clinic';const esc=s=>String(s||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
r.get('/',async(req,res)=>{const q=String(req.query.q||'').trim();const f=q?{$or:[{name:{$regex:esc(q),$options:'i'}},{type:{$regex:esc(q),$options:'i'}},{barcode:{$regex:esc(q),$options:'i'}}]}:{};res.json(await Medicine.find(f).sort({name:1}))});
r.post('/quick-create',allow('Admin','Doctor','Senior Staff'),async(req,res)=>{try{const name=String(req.body.name||'').trim().replace(/\s+/g,' ');if(!name)return res.status(400).json({message:'Medicine name is required'});let medicine=await Medicine.findOne({name:{$regex:`^${esc(name)}$`,$options:'i'}});if(medicine)return res.json({medicine,created:false});medicine=await Medicine.create({name,type:req.body.type||'Unspecified',unit:req.body.unit||'units',stock:0,price:Number(req.body.price||0)});await logActivity(req,'Medicine Quick Added','medicine',medicine._id,`${medicine.name} (stock 0)`);res.status(201).json({medicine,created:true})}catch(e){res.status(400).json({message:e.code===11000?'Medicine already exists':e.message})}});
r.post('/',allow('Admin','Senior Staff'),async(req,res)=>{try{const m=await Medicine.create(req.body);await logActivity(req,'Medicine Added','medicine',m._id,m.name);res.status(201).json(m)}catch(e){res.status(400).json({message:e.code===11000?'Medicine already exists':e.message})}});
r.patch('/:id',allow('Admin','Senior Staff'),async(req,res)=>{const m=await Medicine.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!m)return res.status(404).json({message:'Medicine not found'});await logActivity(req,'Medicine Updated','medicine',m._id,m.name);res.json(m)});
r.post('/:id/image',allow('Admin','Senior Staff'),imageUpload.single('image'),async(req,res)=>{if(!req.file)return res.status(400).json({message:'Image is required'});const m=await Medicine.findById(req.params.id);if(!m)return res.status(404).json({message:'Medicine not found'});if(m.imagePublicId)await deleteCloudinaryAsset(m.imagePublicId,m.imageResourceType,m.imageDeliveryType);const result=await uploadBuffer(req.file.buffer,{folder:`${folder()}/medicines/${m._id}`,public_id:'product',overwrite:true,type:'upload'});m.imageUrl=result.secure_url;m.imagePublicId=result.public_id;m.imageResourceType=result.resource_type;m.imageDeliveryType=result.type;await m.save();res.json(m)});
r.post('/import/csv',allow('Admin','Senior Staff'),upload.single('csv'),async(req,res)=>{if(!req.file)return res.status(400).json({message:'CSV file required'});const parsed=Papa.parse(req.file.buffer.toString('utf8'),{header:true,skipEmptyLines:true});let added=0;for(const row of parsed.data){const name=String(row.Name||row.name||'').trim();if(!name)continue;try{await Medicine.create({name,type:row.Type||row.type||'',unit:row.Unit||row.unit||'units',stock:Number(row['Stock Limit']||row.stock||0),price:Number(row['Price per unit']||row.price||0)});added++}catch{}}res.json({message:`${added} medicines imported`,added})});
export default r;
