import {useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import {Printer,ArrowLeft} from 'lucide-react';
import api from '../services/api';

const Val=({children})=><span className="print-value">{children||'-'}</span>;
const Row=({label,value})=><div className="print-pair"><b>{label}</b><Val>{value}</Val></div>;

export function NabhPrint(){
 const {caseId}=useParams(); const [data,setData]=useState(null);
 useEffect(()=>{let ok=true;(async()=>{const r=await api.get(`/cases/${caseId}`);if(ok)setData(r.data)})().catch(()=>{});return()=>{ok=false}},[caseId]);
 if(!data)return <div className="screen-center">Loading case paper…</div>;
 const c=data.casePaper,p=c.patient||{},items=data.prescription?.items||[];
 const singles=items.filter(x=>!x.comboId),groups=Object.values(items.filter(x=>x.comboId).reduce((a,x)=>{(a[x.comboId]??=[]).push(x);return a},{}));
 return <div className="print-screen"><div className="print-toolbar"><button onClick={()=>history.back()}><ArrowLeft size={16}/>Back</button><button className="print-primary" onClick={()=>window.print()}><Printer size={16}/>Print OPD Sheet (A4)</button></div><article className="a4-sheet nabh-sheet">
  <header className="a4-header"><div><h1>AYURVEDIC CASE PAPER</h1><p>NABH-aligned clinical record</p></div><div className="a4-id"><b>{p.patientCode}</b><span>{new Date(c.createdAt).toLocaleDateString()}</span></div></header>
  <section className="clinical-box"><h2>Patient Details</h2><div className="print-grid four"><Row label="Patient" value={p.name}/><Row label="Age / Gender" value={`${p.age||'-'} / ${p.gender||'-'}`}/><Row label="Phone" value={p.phone}/><Row label="Doctor" value={c.doctor?.name}/><Row label="Allergies" value={p.allergies}/><Row label="Prakriti" value={c.prakriti||p.prakriti}/><Row label="Follow-up" value={c.followUpDate?new Date(c.followUpDate).toLocaleDateString():''}/><Row label="Created" value={new Date(c.createdAt).toLocaleString()}/></div></section>
  <section className="clinical-box"><h2>Clinical History</h2><div className="print-grid two"><Row label="Chief Complaints" value={c.chiefComplaints}/><Row label="Systemic Examination" value={c.systemicExamination}/><Row label="Ahar / Vihar" value={c.aharVihar}/><Row label="Notes" value={c.notes}/></div></section>
  <section className="clinical-box"><h2>Ashtavidha Pariksha</h2><div className="print-grid four"><Row label="Nadi" value={c.nadi}/><Row label="Mutra" value={c.mutra}/><Row label="Mala" value={c.mala}/><Row label="Jivha" value={c.jivha}/><Row label="Shabda" value={c.shabda}/><Row label="Sparsha" value={c.sparsha}/><Row label="Druk" value={c.druk}/><Row label="Akruti" value={c.akruti}/></div></section>
  <section className="clinical-box"><h2>Dashavidha / Ayurvedic Assessment</h2><div className="print-grid five"><Row label="Prakriti" value={c.prakriti}/><Row label="Vikriti" value={c.vikriti}/><Row label="Sara" value={c.sara}/><Row label="Samhanana" value={c.samhanana}/><Row label="Pramana" value={c.pramana}/><Row label="Satmya" value={c.satmya}/><Row label="Sattva" value={c.sattva}/><Row label="Agni" value={c.agni}/><Row label="Vyayama Shakti" value={c.vyayamaShakti}/></div></section>
  <section className="clinical-box"><h2>Modern Parameters</h2><div className="print-grid four"><Row label="BP" value={c.bp}/><Row label="Pulse" value={c.pulse}/><Row label="Weight" value={c.weight}/><Row label="Temperature" value={c.temp}/></div></section>
  <section className="clinical-box"><h2>Ayurvedic Diagnosis</h2><div className="print-grid five"><Row label="Diagnosis" value={c.diagnosis}/><Row label="Dosha" value={c.diagDosha}/><Row label="Dushya" value={c.diagDushya}/><Row label="Srotas" value={c.diagSrotas}/><Row label="Agni" value={c.diagAgni}/><Row label="Ama" value={c.diagAma}/></div></section>
  <section className="clinical-box"><h2>Investigations</h2><div className="print-grid two"><Row label="Prescribed" value={c.investigationsPrescribed}/><Row label="Records / Findings" value={c.investigationsRecords}/></div></section>
  <section className="clinical-box"><h2>Prescription</h2>{!items.length?<p className="print-empty">No medicines prescribed.</p>:<table className="print-table"><thead><tr><th>Medicine</th><th>Unit Dose</th><th>Dosage</th><th>Duration</th><th>Qty</th></tr></thead><tbody>{singles.map((x,i)=><tr key={`s${i}`}><td>{x.medicine?.name}</td><td>-</td><td>{x.dosage}</td><td>{x.duration}</td><td>{x.quantity}</td></tr>)}{groups.map((g,gi)=>g.map((x,i)=><tr key={`g${gi}-${i}`}><td><b>{i===0?`Combination ${gi+1}: `:''}</b>{x.medicine?.name}</td><td>{x.unitDose||'-'}</td><td>{i===0?x.dosage:'↳'}</td><td>{i===0?x.duration:'↳'}</td><td>{i===0?x.quantity:'↳'}</td></tr>))}</tbody></table>}</section>
  <footer className="signature-row"><div>Patient / Attendant Signature</div><div><b>{c.doctor?.name||'Doctor'}</b><br/>Doctor Signature</div></footer>
 </article></div>
}

export function InvoicePrint(){
 const {billingId}=useParams(); const [data,setData]=useState(null),[settings,setSettings]=useState({});
 useEffect(()=>{let ok=true;(async()=>{const [b,s]=await Promise.all([api.get(`/billing/${billingId}`),api.get('/settings')]);if(ok){setData(b.data);setSettings(s.data)}})().catch(()=>{});return()=>{ok=false}},[billingId]);
 if(!data)return <div className="screen-center">Loading invoice…</div>;
 const b=data.billing,p=b.patient||{},items=data.prescription?.items||[];
 return <div className="print-screen"><div className="print-toolbar"><button onClick={()=>history.back()}><ArrowLeft size={16}/>Back</button><button className="print-primary" onClick={()=>window.print()}><Printer size={16}/>Print Invoice</button></div><article className="a4-sheet invoice-sheet"><header className="invoice-header"><div className="invoice-brand">{settings.clinic_logo&&<img src={settings.clinic_logo}/>}<div><h1>{settings.clinic_name||'Ayurvedshala'}</h1><p>{settings.clinic_address}</p><p>{[settings.clinic_phone,settings.clinic_email].filter(Boolean).join(' · ')}</p>{settings.clinic_gst&&<p>GST: {settings.clinic_gst}</p>}</div></div><div className="invoice-meta"><span>INVOICE</span><b>{b.invoiceNo}</b><small>{new Date(b.createdAt).toLocaleString()}</small></div></header>
 <section className="invoice-to"><div><small>BILL TO</small><h3>{p.name}</h3><p>{p.patientCode} · {p.phone||''}</p><p>{p.address||''}</p></div><div><small>CONSULTING DOCTOR</small><h3>{b.casePaper?.doctor?.name||'-'}</h3><p>{b.paymentMethod||'Cash'} · {b.status}</p></div></section>
 <table className="invoice-table"><thead><tr><th>Description</th><th className="right">Qty</th><th className="right">Rate</th><th className="right">Amount</th></tr></thead><tbody>{!b.isManual&&<tr><td>Consultation Fee</td><td className="right">1</td><td className="right">₹{Math.max(0,Number(b.subtotal||0)-items.reduce((s,x)=>s+Number(x.price||0)*Number(x.quantity||0),0)).toFixed(2)}</td><td className="right">Included</td></tr>}{items.map((x,i)=><tr key={i}><td>{x.comboId&&<small className="combo-label">Combination</small>} {x.medicine?.name}<small>{[x.unitDose,x.dosage,x.duration].filter(Boolean).join(' · ')}</small></td><td className="right">{x.quantity}</td><td className="right">₹{Number(x.price||0).toFixed(2)}</td><td className="right">₹{(Number(x.price||0)*Number(x.quantity||0)).toFixed(2)}</td></tr>)}{b.isManual&&!items.length&&<tr><td>Clinical services / Manual billing</td><td className="right">1</td><td className="right">₹{Number(b.totalAmount||0).toFixed(2)}</td><td className="right">₹{Number(b.totalAmount||0).toFixed(2)}</td></tr>}</tbody></table>
 <div className="invoice-summary"><RowLine label="Subtotal" value={b.subtotal}/><RowLine label="Discount" value={b.discount}/><RowLine label="Total" value={b.totalAmount} strong/><RowLine label="Paid" value={b.amountPaid}/><RowLine label="Outstanding" value={b.outstanding} strong={Number(b.outstanding)>0}/></div>
 {b.payments?.length>0&&<section className="payment-history"><h3>Payments</h3>{b.payments.map((x,i)=><div key={i}><span>{new Date(x.createdAt||b.createdAt).toLocaleString()} · {x.paymentMethod}</span><b>₹{Number(x.amount||0).toFixed(2)}</b></div>)}</section>}
 <footer className="invoice-footer"><p>{settings.print_footer||'Thank you. Please keep this invoice for your records.'}</p><div>Authorised Signature</div></footer></article></div>
}
function RowLine({label,value,strong}) {return <div className={strong?'strong':''}><span>{label}</span><b>₹{Number(value||0).toFixed(2)}</b></div>}
