import {useEffect,useMemo,useRef,useState} from 'react';import {NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';import {LayoutDashboard,UsersRound,Stethoscope,ClipboardCheck,CalendarDays,FileScan,ReceiptText,Pill,ChartNoAxesCombined,UserCog,Database,History,Settings,LogOut,Menu,X,Search,Plus,Moon,Sun,Bell,TriangleAlert,CalendarCheck,PanelLeftClose} from 'lucide-react';import {useAuth} from '../context/AuthContext';import api from '../services/api';
const Link=({to,icon:Icon,children,end=false})=><NavLink to={to} end={end} className={({isActive})=>`sidebar-link ${isActive?'active':''}`}><Icon size={19}/><span>{children}</span></NavLink>;
export default function Layout(){const {user,logout}=useAuth();const location=useLocation(),nav=useNavigate();const [mobile,setMobile]=useState(false),[collapsed,setCollapsed]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('clinic_theme')==='dark'),[settings,setSettings]=useState({clinic_name:'Ayurvedshala'}),[q,setQ]=useState(''),[results,setResults]=useState([]),[searchOpen,setSearchOpen]=useState(false),[notice,setNotice]=useState(false),[stats,setStats]=useState({lowStock:0,followupsToday:0});const timer=useRef();
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('clinic_theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{let alive=true;(async()=>{try{const [s,d]=await Promise.all([api.get('/settings'),api.get('/dashboard')]);if(alive){setSettings(s.data);setStats(d.data)}}catch{}})();return()=>{alive=false}},[location.pathname]);
 useEffect(()=>{clearTimeout(timer.current);if(q.trim().length<2){setResults([]);setSearchOpen(false);return}timer.current=setTimeout(async()=>{try{const {data}=await api.get('/search',{params:{q}});setResults(data);setSearchOpen(true)}catch{}},250);return()=>clearTimeout(timer.current)},[q]);
 const title=useMemo(()=>({'/':'dashboard','/patients':'patients','/today-opd':"today's opd",'/appointments':'appointments','/investigations':'investigation reports','/billing':'billing','/inventory':'inventory','/analytics':'reports & analytics','/staff':'staff','/master-data':'master data','/activity':'activity log','/settings':'settings'}[location.pathname]||location.pathname.split('/').filter(Boolean).at(-1)||'dashboard'),[location.pathname]);
 const initials=(user?.name||'U').slice(0,1).toUpperCase();const operations=['Admin','Senior Staff','Junior Staff','Reception','Accountant'].includes(user?.role);const canInventory=['Admin','Senior Staff','Junior Staff'].includes(user?.role);
 return <div className={`erp-shell ${collapsed?'sidebar-collapsed':''}`}>
  {mobile&&<div className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}<aside className={`sidebar ${mobile?'open':''}`}><div className="sidebar-brand"><NavLink to="/" className="brand-link"><div className="brand-logo">{settings.clinic_logo?<img src={settings.clinic_logo}/>:<Stethoscope/>}</div>{!collapsed&&<div><strong>{settings.clinic_name||'Ayurvedshala'}</strong><small>Clinical ERP</small></div>}</NavLink><button className="mobile-only icon-dark" onClick={()=>setMobile(false)}><X size={20}/></button></div>
  <nav><div className="sidebar-section">Workspace</div><Link to="/" icon={LayoutDashboard} end>Dashboard</Link><Link to="/patients" icon={UsersRound}>Patients</Link>{['Admin','Doctor'].includes(user?.role)&&<Link to="/patients?new=1" icon={Stethoscope}>New Consultation</Link>}<Link to="/today-opd" icon={ClipboardCheck}>Today's OPD</Link><Link to="/appointments" icon={CalendarDays}>Appointments</Link><Link to="/investigations" icon={FileScan}>Investigation Reports</Link><div className="sidebar-section">Operations</div>{operations&&<Link to="/billing" icon={ReceiptText}>Billing</Link>}{canInventory&&<Link to="/inventory" icon={Pill}>Inventory</Link>}<Link to="/analytics" icon={ChartNoAxesCombined}>Reports & Analytics</Link>{user?.role==='Admin'&&<><div className="sidebar-section">Administration</div><Link to="/staff" icon={UserCog}>Staff</Link><Link to="/master-data" icon={Database}>Master Data</Link><Link to="/activity" icon={History}>Activity Log</Link><Link to="/settings" icon={Settings}>Settings</Link></>}</nav>
  <div className="sidebar-footer"><div className="profile-card"><div className="avatar-sm">{initials}</div>{!collapsed&&<div className="profile-text"><strong>{user?.name}</strong><small>{user?.role}</small></div>}{!collapsed&&<button onClick={logout} className="icon-dark"><LogOut size={17}/></button>}</div><button className="collapse-btn desktop-only" onClick={()=>setCollapsed(v=>!v)}><PanelLeftClose size={16} className={collapsed?'flip':''}/>{!collapsed&&<span>Collapse sidebar</span>}</button></div>
 </aside><main className="main-shell"><header className="glass-header"><button className="mobile-only icon-btn" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="workspace-title desktop-xl"><small>Workspace</small><h2>{title.replaceAll('-',' ')}</h2></div><div className="global-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>q.length>1&&setSearchOpen(true)} placeholder="Search patients, phone, invoice, medicine, diagnosis..."/>{searchOpen&&<div className="search-results">{results.length?results.map((x,i)=><button key={i} onClick={()=>{nav(x.url);setSearchOpen(false);setQ('')}}><span className="search-icon">{x.type.slice(0,1)}</span><span><strong>{x.label}</strong><small>{x.subtitle}</small></span><em>{x.type}</em></button>):<div className="empty-mini">No matching records found.</div>}</div>}</div><div className="header-actions"><button className="quick-add desktop-only" onClick={()=>nav('/patients?new=1')}><Plus size={16}/>Quick Add</button><button className="icon-btn" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><div className="notice-wrap"><button className="icon-btn" onClick={()=>setNotice(v=>!v)}><Bell size={19}/>{Number(stats.lowStock||0)+Number(stats.followupsToday||0)>0&&<i/>}</button>{notice&&<div className="notice-pop"><strong>Notifications</strong><button onClick={()=>{nav('/inventory');setNotice(false)}}><TriangleAlert size={18}/><span><b>{stats.lowStock||0}</b> low-stock medicine(s)</span></button><button onClick={()=>{nav('/today-opd');setNotice(false)}}><CalendarCheck size={18}/><span><b>{stats.followupsToday||0}</b> follow-up(s) today</span></button></div>}</div><div className="date-chip desktop-xl"><strong>{new Date().toLocaleDateString(undefined,{weekday:'short',day:'2-digit',month:'short',year:'numeric'})}</strong><small>{user?.role}</small></div></div></header><section className="content page-enter"><Outlet/></section></main>
 </div>}
